services:
  keycloak_db:
    container_name: keycloak_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=testdb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_keycloak_db:/var/lib/postgresql/data/

  keycloak_svc:
    container_name: identity
    environment:
      - KEYCLOAK_ADMIN=admin    
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://keycloak_db/testdb?currentSchema=identity
      - KC_DB_USERNAME=postgres
      - KC_DB_PASSWORD=postgres
    restart: always
    ports:
      - "9090:8080"
    command:
      - start-dev